# Generated by Django 4.1.7 on 2023-03-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uimg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
