# Generated by Django 4.1.7 on 2023-03-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_users_uimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(),
        ),
    ]
