# Generated by Django 4.1.7 on 2023-04-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('message', models.TextField()),
                ('to', models.IntegerField()),
                ('from_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.IntegerField()),
                ('cid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('from_user', models.CharField(max_length=30)),
                ('to_user', models.CharField(max_length=30)),
            ],
        ),
    ]
