# Generated by Django 4.1.7 on 2023-03-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0002_users_uimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('writer', models.CharField(max_length=30)),
                ('bimg', models.ImageField(blank=True, upload_to='image')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to='app01.users')),
            ],
        ),
    ]
