# Generated by Django 4.1.7 on 2023-03-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_users_uimg'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.users')),
            ],
        ),
    ]
